spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: gus02031365@gmail.com
    password: lldh prba yfkw jfkq
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  datasource:
    url: jdbc:mysql://localhost:3306/semi_db?useSSL=false&serverTimezone=Asia/Seoul
    username: root         # ← 본인 DB 사용자 이름
    password: "" # ← 본인 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create   # 또는 validate / create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379

riot:
  api:
    key: RGAPI-c391455b-005b-4f1a-8942-ebbacfc86f51
    riotregion-url: https://asia.api.riotgames.com
    platform-url: https://kr.api.riotgames.com
    match-url: https://asia.api.riotgames.com
    lol-match-prefix: /lol/match/v5
    tft-match-prefix: /tft/match/v1

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

jwt:
  secret: your-very-secret-jwt-signing-key-here-please-change-it
  expiration: 86400000  # 1일 (밀리초 단위)